version: "3"
services:
  frontend:
    container_name: kanban_frontend
    stdin_open: true # https://github.com/facebook/create-react-app/issues/8688
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kanban/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend
  backend:
    container_name: kanban_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kanban/backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="kanban"
      - MONGODB_PASS="kanban"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
